config/routes.rb
FacilityReview::Application.routes.draw do
  root "facilities#location"
  # post "facilities" => "facilities#index"
  get "facilities" => "facilities#index"
  get "facilities/:id" => "facilities#show", as: "facility"

  resources :facilities do
    member do
      post 'create_scrivito_obj'
    end
    resources :reviews
  end

  # Default Scrivito routes. Adapt them to change the routing of CMS objects.
  # See the documentation of 'scrivito_route' for a detailed description.
  scrivito_route '/', using: 'homepage'
  scrivito_route '(/)(*slug-):id', using: 'slug_id'
  scrivito_route '/*permalink', using: 'permalink', format: false
end

app/models/download.rb
class Download < Obj
  attribute :blob, :binary
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  # geocoded_by :address ||  :IP address
  # after_validation :geocode

  def recent_reviews
    reviews.order('created_at desc').limit(2)
  end
end

app/models/facility_data.rb
class FacilityData < Obj
  attribute :body, :widgetlist
  attribute :facility_id, :string

  def self.scrivito_id_for_facility(facility)
    Digest::SHA1.hexdigest("facility-#{facility.id}")[0...16]
  end

  def self.create_for(facility)
    create(_id: scrivito_id_for_facility(facility), facility_id: facility.id)
  end

  def self.find_for(facility)
    find(scrivito_id_for_facility(facility))
  end
end

app/models/facility_fetcher.rb
class FacilityFetcher < ActiveRecord::Base

  validates :location, :presence => true
  after_create :get_lat_long

  def get_lat_long
    results = Geocoder.search(location)
    latitude = results.first.data["geometry"]["location"]["lat"]
    longitude = results.first.data["geometry"]["location"]["lng"]
    update(:latitude => latitude, :longitude => longitude) if latitude && longitude
  end

  def get_facilities
    response = Faraday.get "https://www.itriagehealth.com/api/v1/medical_providers.json?search_model=medical_facilities&per_page=20&sort_by=featured&distance=25&medical_facility_categories=2&medical_facility_sub_categories=&family_member_id=null&lat=#{latitude}&lng=#{longitude}"
    response.status
    facilities = JSON.parse(response.body)["results"].map do |facility|
      attributes = {
        :iTriage_id => facility["id"],
        :name       => facility["name"],
        :phone      => facility["phone"],
        :tagline    => facility["tagline"],
        :logo_url   => facility["logo_url"],
        :street     => facility["street"],
        :street2    => facility["street2"],
        :city       => facility["city"],
        :state      => facility["state_abbreviated"],
        :zip        => facility["zip"]
      }
      @facility = Facility.find_or_create_by(attributes)
    end
  end
end

app/models/headline_widget.rb
class HeadlineWidget < Widget
  attribute :headline, :string
end

app/models/image.rb
class Image < Obj
  attribute :blob, :binary

  # activate image resizing and optimization
  def apply_image_transformation?
    true
  end
end

app/models/image_widget.rb
class ImageWidget < Widget
  attribute :image, :reference
end

app/models/obj.rb
class Obj < Scrivito::BasicObj
end

app/models/page.rb
class Page < Obj
  attribute :title, :string
  attribute :body, :widgetlist
  attribute :child_order, :referencelist
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :facility
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :content, length: { minimum: 11}

end

app/models/text_widget.rb
class TextWidget < Widget
  attribute :text, :html
end

app/models/widget.rb
class Widget < Scrivito::BasicWidget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  include Scrivito::ControllerActions
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  include Scrivito::ControllerHelper
  before_action :fetch_scrivito_object, only: [:show]

  def index
    fetcher = FacilityFetcher.find_or_create_by(:location => params[:location])
    @facilities = fetcher.get_facilities
  end

  def show
    @facility = Facility.find(params[:id])
  end

  def create_scrivito_obj
    set_facility
    FacilityData.create_for(@facility)
    redirect_to facility_path(@facility)
  end

  private

  def set_facility
    @facility = Facility.find(params[:id])
  end

  def fetch_scrivito_object
    set_facility
    @obj =
      begin
        FacilityData.find_for(@facility)
      rescue Scrivito::ResourceNotFound
        # Nothing to do here, handled in template
      end
  end
end

app/controllers/page_controller.rb
class PageController < CmsController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :html, :json
  before_action :set_facility

  def index
    @reviews = @facility.reviews
    respond_with(@reviews)
  end

  def new
    @review = @facility.reviews.new
  end

  def create
    @review = @facility.reviews.new(review_params)
    if @review.save
      redirect_to facility_reviews_path(@facility),
                        notice: "Thank you for your review!"
    else
      render :new
    end
  end

  def destroy
    @review = @facility.reviews.find(params[:id])
    @review.destroy
    redirect_to facility_reviews_path(@facility), notice: "The review has been deleted."
  end

  private

  def review_params
    params.require(:review).permit(:name, :email, :content)
  end

  def set_facility
    @facility = Facility.find(params[:facility_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
  def format_title(facilities)
    if facilities.size == 0
      content_tag(:strong, "No Facilities Found")
    else
      pluralize(@facilities.size, 'Facility')
    end
  end

  def image_for(facility)
    if facility.logo_url.blank? || facility.logo_url.nil?
      image_tag('placeholder.png')
    else
      image_tag(facility.logo_url)
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/download/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for do %>
    <%= scrivito_tag :div, @obj, :blob do %>
      <%= link_to @obj.description_for_editor, scrivito_path(@obj), :target => :blank %>
    <% end %>
  <% end %>

  <%= scrivito_details_for do %>
    <%= number_to_human_size @obj.meta_data[:content_length] %>
  <% end %>
<% end %>

app/views/facilities/index.html.erb
<h1> <%= link_to (format_title(@facilities)), root_path %> found</h1>
<ul id="facilities">
  <% @facilities.each do |facility| %>
    <li>
      <article class="facility">
        <header>
           <%= image_for(facility) %>
          <h2><%= link_to facility.name, facility %></h2>
        </header>
        <p>
          <%= truncate(facility.tagline.to_s.html_safe, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Phone</th>
            <td><%= number_to_phone(facility.phone, area_code: true) %></td>
          </tr>
          <tr>
            <th>Address</th>
            <td>
              <%= facility.street %>
              <%= facility.city %>
              <%= facility.state %>
              <%= facility.zip %>
            </td>
          </tr>
          <tr>
            <th>iTriage ID</th>
            <td><%= facility.iTriage_id %></td>
          </tr>
        </table>
        <footer>
          <%= link_to pluralize(facility.reviews.size, "Review"), facility_reviews_path(facility), class: 'button' %>
         <%= link_to "Select Facility", facility_path(facility), class: 'button' %>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/facilities/location.html.erb
  <fieldset id="location">
  <ol>
    <li class="required">
      <%= form_tag("facilities", method: "post") do %>
        <%= label_tag(:location) %>
        <%= text_field_tag(:location) %>
        <%= submit_tag("Submit") %>
      <% end %>
    </li>
    OR
    <br>
    <br>
      <%= link_to "Find Facilities Near Me", facilities_path(:location => "Denver, CO"), class: 'button' %>
  </ol>
</fieldset>
<br>
<br>
<center> Medical Facility Review allows you to find Urgent Care Facilities near your input location and add reviews of your own, or read reviews of others to help make an informed choice for your care. Enjoy!</center>

app/views/facilities/show.html.erb
<article id="facility" class="facility">

  <% if @obj %>
    <%= scrivito_tag :div, @obj, :body %>
  <% elsif scrivito_in_editable_view? %>
    <%= link_to "Provide facility data", create_scrivito_obj_facility_path(@facility) ,method: 'POST'%>
  <% end %>

  <header>
    <%= image_for(@facility) %>
    <h1><%= @facility.name %></h1>
  </header>

  <p>
    <%= @facility.tagline.to_s.html_safe %>
  </p>

  <h3 class="no-rule">
    <%= number_to_phone(@facility.phone, area_code: true) %>
  </h3>

  <h3> Address:</h3>
  <p>
    <%= @facility.street %><br>
    <%= @facility.city %>,
    <%= @facility.state %><br>
    <%= @facility.zip %>
  </p>
  <h3>iTriage Facility ID:</h3>
  <p>
    <%= @facility.iTriage_id %>
  </p>
    <% if @facility.recent_reviews.any? %>
      <h3>Recent Reviews</h3>
      <ol id="reviews">
        <% @facility.recent_reviews.each do |review| %>
          <span class="review">Review By: <%= review.name %></span><br/>
          <span calss="date">Submitted: <%= time_ago_in_words(review.created_at) %> ago</span><br/>
          <span class="review">Review: "<%= review.content %>"</span><br><br/><br/>
        <% end %>
      </ol>
      <p>
        Read all <%= link_to pluralize(@facility.reviews.size, "review"), facility_reviews_path(@facility) %>
      </p>
    <% end %>
    <footer>
    <nav>
      <%= link_to pluralize(@facility.reviews.size, "Review"), facility_reviews_path(@facility), class: 'button' %>
      <%= link_to 'Submit Review', new_facility_review_path(@facility), class: 'button' %>
      <%= link_to "Back to All Facilities", facilities_path, class: 'button' %>
    </nav>
  </footer>
</article>

app/views/headline_widget/show.html.erb
<%= scrivito_tag :h2, widget, :headline %>

app/views/headline_widget/thumbnail.html.erb
<%= scrivito_thumbnail HeadlineWidget.description_for_editor, :headline do %>
  A headline widget.
<% end %>

app/views/image/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for do %>
    <%= scrivito_image_tag @obj %>
  <% end %>

  <%= scrivito_details_for do %>
    <% if @obj.meta_data[:width] && @obj.meta_data[:height]%>
      <div>
        <%= @obj.meta_data[:width] %> × <%= @obj.meta_data[:height] %> px
      </div>
    <% end %>

    <div>
      <%= number_to_human_size @obj.meta_data[:content_length] %>
    </div>
  <% end %>
<% end %>

app/views/image_widget/show.html.erb
<%= scrivito_image_tag widget, :image %>

app/views/image_widget/thumbnail.html.erb
<%= scrivito_thumbnail ImageWidget.description_for_editor, :image do %>
  A widget with an image.
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Agsiegert','http://github.com/agsiegert' %>
  </p>
  <p style="font-size:10px;">This system uses iTriages API to look up Urgent Care Facilities near your input location and provides a those reviews in an API in JSON format.</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Medical Facility Review', root_path %></h1>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-facilities">
        <%= link_to 'All Facilities', facilities_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= scrivito_head_tags %>
  <title>Medical Facility Review</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<%= notice %>

<div id="wrapper">

  <div id="container">

    <section id="content">
      <%= yield %>
      <%= scrivito_body_tags %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/layouts/scrivito_dialog.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= scrivito_head_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="scrivito_dialog">
  <%= scrivito_body_tags %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/page/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for "Title" do %>
    <%= scrivito_tag :div, @obj, :title %>
  <% end %>
<% end %>

app/views/page/index.html.erb
<div>
  <p><%= link_to 'Home', scrivito_path(Obj.root) %></p>

  <%= scrivito_tag_list :ul, Obj.root, :toclist do |list, page| %>
    <%= list.tag :li do %>
      <%= link_to page.display_title, scrivito_path(page) %>
    <% end %>
  <% end %>

  <% if Obj.root.toclist.empty? && scrivito_in_editable_view? %>
    <p>(Hint: Click on the Scrivito icon to the right to create the first subpage.)</p>
  <% end %>
</div>

<%= scrivito_tag :h1, @obj, :title %>
<%= scrivito_tag :div, @obj, :body %>

app/views/page/thumbnail.html.erb
<%= scrivito_thumbnail Page.description_for_editor, :content %>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@facility.name, @facility) %></h1>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
  <li>
      <span class="review">By: <%= review.name %></span><br>
      <span class="user">Email: <%= review.email %></span><br>
      <span calss="date">Submitted: <%= time_ago_in_words(review.created_at) %> ago</span>
    <p>
      &quot;<%= review.content %>&quot;
    </p>
  </li>
    <p>
      <%= link_to "Delete Review", facility_review_path(@facility, review), :method => :delete,  class: 'button' %>
    </p>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to(@facility.name, @facility) %></h1>
</header>

<%= form_for([@facility, @review]) do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.text_field :email, size: 60 %>
      </li>
      <li class="required">
        <%= f.label :content %>
        <%= f.text_area :content, cols: 120, placeholder: "Tell us about your experience." %>
      </li>
    </ol>
    <p>
      <%= f.submit "Submit Review" %>
      <%= link_to "Cancel", @facility, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/text_widget/show.html.erb
<%= scrivito_tag :div, widget, :text %>

app/views/text_widget/thumbnail.html.erb
<%= scrivito_thumbnail TextWidget.description_for_editor, :text do %>
  A widget for HTML content.
<% end %>